version: "3.9"

services:
  postgres:
    image: postgres:11.18-alpine
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      # Use pg_isready to check postgres is running. Substitute different
      # user `postgres` if you've setup differently to config/pgpass-mainnet
      test: ["CMD-SHELL", "pg_isready -U cardano-db-sync -d cardano-db-sync"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ${POSTGRES_ARGS:--c maintenance_work_mem=1GB -c max_parallel_maintenance_workers=4}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-node:
    image: inputoutput/cardano-node:${CARDANO_NODE_VERSION:-8.0.0}
    environment:
      - NETWORK=${NETWORK:-mainnet}
    volumes:
      - node-db:/data/db
      - node-ipc:/ipc
    restart: on-failure
    healthcheck:
      # Ping the EKG port to see if it responds.
      # Assuming if EKG isn't up then the rest of cardano-node isn't either.
      test: ["CMD-SHELL", "curl -f 127.0.0.1:12788 || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-db-sync:
    image: inputoutput/cardano-db-sync:${CARDANO_DB_SYNC_VERSION:-13.1.1.3}
    environment:
      - NETWORK=${NETWORK:-mainnet}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-}
      - RESTORE_RECREATE_DB=N
      - EXTRA_DB_SYNC_ARGS=${EXTRA_DB_SYNC_ARGS:-}
    depends_on:
      # Depend on both services to be healthy before starting.
      cardano-node:
        condition: service_healthy
      postgres:
        condition: service_healthy
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - db-sync-data:/var/lib/cexplorer
      - node-ipc:/node-ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    # snapshots provided by RESTORE_SNAPSHOT env var will be downloaded to the working dir
    working_dir: /var/lib/cexplorer

  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - postgres:db_host
    environment:
      PGRST_DB_URI: postgres://${POSTGREST_USER}:${POSTGREST_PASSWORD}@db_host/${POSTGREST_DB}
      PGRST_DB_SCHEMA: public
      #IMPORTANT: In production this role should not be the same as the one used for the connection:
      PGRST_DB_ANON_ROLE: ${POSTGREST_USER}
      PGRST_SERVER_PROXY_URI: "http://127.0.0.1:3000"
    depends_on:
      postgres:
        condition: service_healthy

  swagger:
    image: swaggerapi/swagger-ui
    ports:
        - "8080:8080"
    expose:
        - "8080"
    environment:
        API_URL: http://external_postgrest_ip:3000/
    depends_on:
      postgres:
        condition: service_healthy


  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: zxpectre@gamechanger.finance
        PGADMIN_DEFAULT_PASSWORD: 12345678
        PGADMIN_LISTEN_PORT: 80
    ports:
        - "5050:80"
    links:
        - "postgres:pgsql-server"
    volumes:
        - pgadmin-data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy


secrets:
  postgres_db:
    file: ./config/secrets/cardano-db-sync/postgres_db
  postgres_password:
    file: ./config/secrets/cardano-db-sync/postgres_password
  postgres_user:
    file: ./config/secrets/cardano-db-sync/postgres_user

volumes:
  db-sync-data:
  postgres:
  node-db:
  node-ipc:
  pgadmin-data:
